### ISSUE TITLE
Provide a Gentoo ebuild package

### ISSUE THREAD

**Issue by ASmith-** [blueprint-freespeech/ricochet-refresh#110]
Provide a Gentoo ebuild package

Please take a moment to provide a Gentoo ebuild package for Gentoo users. 

I'm actively using and recommending Ricochet Refresh a free, open source lightweight secure, anonymous utility for many of my online friends. Kudos and thanks to the Ricochet Refresh developers to refresh the Ricochet project, update it for the v3 Onion network and improve upon this nifty messenger.

**Comment by pospeselr** [comment]
This is not something we are able to support (we can only maintain so many packages). We'd be happy to make w/e changes (within reason) to let someone in the community maintain a Ricochet-Refresh Gentoo package.
