### ISSUE TITLE
Use OpenPGP to encrypt/decrypt the message

### ISSUE THREAD

**Issue by awtbrain** [blueprint-freespeech/ricochet-refresh#113]
https://github.com/ricochet-im/ricochet/blob/master/doc/protocol.md

If your app is just sending normal message over Tor connection it is lazy & not encrypted.

**Comment by milahu** [comment]
the encryption is provided by tor.
thats why tor-hidden websites use http, not https

**Comment by pospeselr** [comment]
We rely on tor's onion routing protocol to provide encryption.
