### ISSUE TITLE
libxcb-icccm missing

### ISSUE THREAD

**Issue by ATW136** [blueprint-freespeech/ricochet-refresh#120]
Debian Testing (after Bullseye release)

Download:  ricochet-refresh-3.0.10-linux-x86_64.tar

During execution of ./ricochet-refresh, libxcb-icccm.so:4 could not be opened. Missing.

Executed apt install torbrowser-launcher.

Can now use ricochet-refresh.

ATW

**Comment by pospeselr** [comment]
The fix here is to install libxcb-icccm4 (presumably torbrowser-launcher pull that down). Our next release in the coming weeks will include a .deb which should hopefully take care of this automatically on debian-baed systems.

**Comment by pospeselr** [comment]
Duplicate of #23
