### ISSUE TITLE
Is ricochet-refresh stable?

### ISSUE THREAD

**Issue by pymnh** [blueprint-freespeech/ricochet-refresh#121]
happy to see ricochet lives on by this fork. thank you for your work

the website and the releases overview suggest ricochet-refresh 3.0.10 is a stable release ready for use, but the readme says the opposite. is the readme only lagging behind? could you please clarify?

**Comment by pospeselr** [comment]
The README is lagging a fair bit behind (see #105). 

Ricochet-Refresh is 'stable' and currently in maintenance-mode while we work on the various outstanding issues.
