### ISSUE TITLE
New contact format to share IDs

### ISSUE THREAD

**Issue by evilmennot** [blueprint-freespeech/ricochet-refresh#129]
You could introdude new contact format:

```
Hey thanks for inviting me pizza party yesterday!
Contact me later!

---- BEGIN RR2 CONTACT -----
g6gf8egervbherveverbvebrvybve
wbrfbyeyvberyvbaervbyeibvybve
---- END RR2 CONTACT -----

Cheers,
Bro
```

- At a glance one cannot know what the original onion name is.
- Format
  -  ---BEGIN---, encoded data, ---END---.
  - encoded data
     - array of
       - version; 3
       - onion name; xxxxxxxxxxxx.onion
       - secret key; xyzxyzxyz(if this is per-contact ID #111) or "null" (if public ID)

**Comment by m-simonelli** [comment]
What exactly does this add over this?:
```
Hey thanks for inviting me to pizza!
Contact me!

ricochet:l5satjgud6gucryazcyvyvhuxhr74u6ygigiuyixe3a6ysis67ororad

Cheers,
M
```

If #111 is worked on, secret keys can be negotiated on introduction, and shouldn't be given as part of the contact AFAIK
