### ISSUE TITLE
Android version ?

### ISSUE THREAD

**Issue by 002gRTEah3mRYH** [blueprint-freespeech/ricochet-refresh#130]
Will it be available ?

Thanks

**Comment by pospeselr** [comment]
No mobile versions are currently funded or planned

**Comment by milahu** [comment]
possible solutions

- expand ricochet to use [Qt for Android](https://doc.qt.io/qt-6/android.html)
  - [Porting to Android](https://doc.qt.io/qt-6/porting-to-android.html)
  - [How to Port From Desktop to Mobile](https://wiki.qt.io/How_to_Port_From_Desktop_to_Mobile)
- rewrite ricochet in java
- add ricochet support to an existing chat app
  - [Conversations](https://codeberg.org/iNPUTmice/Conversations) XMPP client (via [ChatSecureAndroid](https://github.com/guardianproject/ChatSecureAndroid))
  - [chat-sdk-android](https://github.com/chat-sdk/chat-sdk-android) XMPP client

**Comment by maltfield** [comment]
If you're not *opposed* to an android version, then can you please re-open this ticket?

Just tag it with "contributions welcome" or "PR welcome" or similar.
