### ISSUE TITLE
[Question] Is obfs4 used?

### ISSUE THREAD

**Issue by odiferousmint** [blueprint-freespeech/ricochet-refresh#131]
If it is not, could potentially set the `ClientTransportPlugin` to `obfs4 exec /usr/local/bin/obfs4proxy` or just `$(pwd)/obfs4proxy` or what have you. It would make sense in this case, too, right?

If it makes sense to use it, might write a script that fetches the latest binaries of tor and obfs4proxy.

**Comment by yanmaani** [comment]
Opening settings and going to the "Tor" tab seems to give me some anti-censorship settings, try there?

**Comment by ASmith-** [comment]
Wouldn't your contacts downstream need to also have obfs4 active on their Ricochet-refresh end as well?

**Comment by cypherbits** [comment]
> Wouldn't your contacts downstream need to also have obfs4 active on their Ricochet-refresh end as well?

No. Using obfs4 or another bridge only affects you as a client. Since it only affects your connection to the guard node.

**Comment by pospeselr** [comment]
obfs4 is not currently used/packaged, but work is scheduled for PTs *relatively* soon

**Comment by pospeselr** [comment]
Now bundled in 3.0.12

**Comment by michael-trieu-fso** [comment]
3.0.12 installers when? This is critical functionality for me. Without it, my upstream firewall always halts the connection.

**Comment by PacoBell** [comment]
3.0.12 installers when? Obfs4 is critical for me as my upstream firewall blocks all other Tor traffic.

**Comment by pospeselr** [comment]
3.0.12 installer are up on github, but the have a bug that won't be fixed until next week preventing adding of new contacts. I expect signed/uploaded 3.0.13 builds early next week.
