### ISSUE TITLE
Build on OSX eats whitespace after terminating punctuation during text entry

### ISSUE THREAD

**Issue by midnightmagic** [blueprint-freespeech/ricochet-refresh#137]
As of commitid e1cc61f7cca6dff1977bf781b7bd461fd0553d25, on OSX a brew-lib linked build (and also the most-recent release build for that matter) eats whitespaces after punctuation during text entry. A period-after-space doesn't enter a visible space after the period. This makes using it difficult.

It's pretty easy to reproduce. You literally just have to run it and try to use it.

qt@5/5.15.2_1

Additional details available on request. Platform is M1.

**Comment by m-simonelli** [comment]
Hi @midnightmagic,
Can you send your CMake configure line? I haven't gotten around to writing the documentation yet, but the toolchain files *shouldn't* be needed when building against brew libs.

**Comment by m-simonelli** [comment]
Ah I think I see what you mean - this happens with the static builds we get out of ricochet-build as well. IIRC this has been an issue for a while, and it's not actually eating the whitespace, it just doesn't render properly. See the following:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/60584156/147714460-1968dfd8-fe58-47a9-b086-1b2abf9becb0.png">
<img width="256" alt="image" src="https://user-images.githubusercontent.com/60584156/147714470-78310f29-a878-4650-8faa-34c20c8810bc.png">

While it looks like the whitespace has been ignored, if I copy and paste the text, it shows the following:
```
test. test
```

Digging around a bit, I found the following bug report for QT, detailing this exact issue - https://bugreports.qt.io/browse/QTBUG-88495

This unfortunately was patched in 5.15.3, which is a commercial only release.

As far as local builds go, I can't really help you that much - but I'll try write up a patch for QT in ricochet-build to fix this.

**Comment by m-simonelli** [comment]
Here's the commit that fixes the issue: https://github.com/qt/qtbase/commit/6d306a0e3755258beb11d7f488c2bb1bf66bec19

**Comment by m-simonelli** [comment]
Hey @midnightmagic, I've opened a MR in ricochet-build with the patch that should fix this - if you want to test it out I've put up (note: unsigned) builds [here](https://msimonelli.xyz/work/tego/prerelease/). The newest build on that page should fix the issue.

Understandably if you don't want to download unsigned builds, you can build from scratch using ricochet-build, but note that will take a while.

**Comment by pospeselr** [comment]
Seems like should be fixed in 3.0.11 with the ricochet-build commit

**Comment by midnightmagic** [comment]
Oh. For some reason I wasn't getting these notifies. Okay! I'll check again with a local build and test with the new patch. If you don't hear from me either I got buried under some other work or it's working!

Thanks guys, really appreciate it.
