### ISSUE TITLE
Update to tor 0.4.7.7

### ISSUE THREAD

**Issue by pospeselr** [blueprint-freespeech/ricochet-refresh#148]
It's coming soon: https://lists.torproject.org/pipermail/tor-project/2022-April/003354.html

**Comment by ASmith-** [comment]
I compiled the newest tor binary v0.4.7.7 and have nearly all of my tor networked applications using it except ricochet-refreshed on my Ubuntu, Linux-Mint platform. I've checked in /home/name/.configure/ricochet-refresh/tor but neither the tor binary nor the geoip, geoip6 files are stored there. I installed the newest tor build so I know ricochet-refreshed is not using that either as its the older v0.4.6 build that is prone to the tor network congestion attacks. So Where IS Ricochet-Refreshed storing the Tor, Geoip, Geoip6 files its using so I can update the tor binary and eliminate that security issue?

**Comment by pospeselr** [comment]
This will be coming soon in 3.0.12

**Comment by m-simonelli** [comment]
Should this be in https://github.com/blueprint-freespeech/ricochet-build?

**Comment by pospeselr** [comment]
Yeah it should have been, but this is resolved with 3.0.12
