### ISSUE TITLE
GLIBC_2.28 not found on Linux

### ISSUE THREAD

**Issue by yabadaba2** [blueprint-freespeech/ricochet-refresh#152]
Hello,

both the Linux AppImage version and the Linux tar.gz version produce the following error when executed on my system:

`/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.28' not found`

My system returns the following:

```
> ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.5) 2.27
```

Can this somehow be fixed or resolved?

**Comment by pospeselr** [comment]
@m-simonelli I thought the whole point of AppImage was that it bundled all the dependencies for us?

**Comment by pospeselr** [comment]
Option 2 sounds reasonable to me.

**Comment by greenpark-code** [comment]
> 2\. Formally define a minimum linux target (i.e. Ubuntu >=12.04)

You'll have to aim higher than 12.04, Ubuntu 18.04.6 has glibc 2.27.

Retrieving and building a .local/lib/glibc-2.28 would be trivial if it weren't for the (in)famous "ELF file ABI version invalid" error which implies also rebuilding gcc (something related with [a feature introduced in 2010](https://stackoverflow.com/questions/7647818/glibc-elf-file-os-abi-invalid) which goal was [to avoid distributing a few more [automated] builds for SPARC64 variants](https://web.archive.org/web/20140308062931/http://vger.kernel.org:80/~davem/cgi-bin/blog.cgi/2010/02/07), which ended up making Linux even more of a moving target).

**Comment by greenpark-code** [comment]
Searching the web it's evident that many users are being affected by the same problem, even on fairly recent Mint installations. 

[Here in GitHub:](https://github.com/spesmilo/electrum/issues/7997#issuecomment-1425155527) the same glibc-2.28 problem affects Electrum (BTC wallet). Somebody (with Ubuntu 18.04.5) points out there that MuseScore4 (music notation software) would require glibc-2.29 BUT the developers also distribute it in **Flatpak** format, which solves the backwards compatibility problem and runs correctly.

**Comment by TNTBOMBOM** [comment]
I have made a ticket (in short) of why someone should choose flatpk over appimage can be found [here](https://github.com/shutter-project/shutter/issues/594).

**Comment by pospeselr** [comment]
Realistically this is going to get fixed by the march of time with people updating before we have an actual fix here.
