### ISSUE TITLE
Ricochet-Refresh is now proprietary

### ISSUE THREAD

**Issue by TNTBOMBOM** [blueprint-freespeech/ricochet-refresh#153]
Hi, 

I saw the license have been [switched to Commons Clause](https://github.com/blueprint-freespeech/ricochet-refresh/commit/b0a274c07f0e8afd7b6727e3fe8428e1f9ad5249) which is [non-free license due to its restrictions](https://www.gnu.org/licenses/license-list.html#comclause).

[Here](https://www.ricochetrefresh.net/#About): 

"Ricochet Refresh uses the original Ricochet open-source software but has improved on it substantially, such as upgrading its security and making it compatible with Tor Onion Services v3 instead of the older v2."

And switched its license to proprietary one, or "but has degraded its license"..

Sad switch, Cant use ricochet anymore..

**Comment by pospeselr** [comment]
lol
