### ISSUE TITLE
Replying to messages

### ISSUE THREAD

**Issue by yanmaani** [blueprint-freespeech/ricochet-refresh#159]
It would be real nice if you could reply to messages. I don't mean a protocol change, just an item in the context menu "Reply". If clicked, it should input to the beginning of the message box something like the following:

```
> It would be real nic... like the following:

```

**Comment by pospeselr** [comment]
I'm not sure I understand how this is meant to work, or the problem it solves.

**Comment by yanmaani** [comment]
**How is this meant to work?**

Next to messages, there could be a little arrow. If you click on it, it quotes a part of the message.

**What problem is this meant to solve?**

If someone sends two messages, and you want to respond to both of them, while making clear which response is intended for which message.

**A**:
> Hey, do you want to go for lunch tomorrow?

**A**:  
> Also, how do you feel about the other thing we discussed earlier?  

**B**:
> Sure

**B**:
> Seems like a good idea

vs

**A**:
> Hey, do you want to go for lunch tomorrow?

**A**:  
> Also, how do you feel about the other thing we discussed earlier?  

**B**:
> > Hey, do you want to go for lunch tomorrow?  

> Sure

**B**:
> > Also, how do you feel about the other thing we discussed earlier?  

> Seems like a good idea
