### ISSUE TITLE
Ubuntu 18.04 Ricochet 1.1.4e error while loading shared libraries: libprotobuf.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by cypherbits** [blueprint-freespeech/ricochet-refresh#16]
`error while loading shared libraries: libprotobuf.so.10: cannot open shared object file: No such file or directory
`

Ubuntu 18.04 and Ricochet Refresh 1.1.4e

**Comment by noneuclideangirl** [comment]
Hmm, interesting. If you install the protobuf libraries via apt or
whatever, does it work then? Could be a simple forgotten include.

**Comment by cypherbits** [comment]
With` sudo apt install protobuf-compiler` it doesn't work.

**Comment by noneuclideangirl** [comment]
I can't reproduce this on my fresh Ubuntu 18.04. Do you have any further details?

**Comment by rezad1393** [comment]
maybe you have older version of protobuf on ubuntu installed 
newer versions have higher number for libprotobuf.so.10 .
for example on archlinux it is libprotobuf.so.18

btw why it is dependent on a external library if it is static?

**Comment by z3ndrag0n** [comment]
@cypherbits this is probably a silly question, but did you try doing:
% sudo apt-get install libprotobuf10

**Comment by cypherbits** [comment]
> @cypherbits this is probably a silly question, but did you try doing:
> % sudo apt-get install libprotobuf10

I'm on Ubuntu 19.10 now and I get the same error. 

And libprotobuf10 is "not available for install".

But don't worry, this project is already deprecated. The new one is Cwtch.im

**Comment by pospeselr** [comment]
Apha build use static protobuf so this is no longer an issue.
