### ISSUE TITLE
Is there any reason the newest release was deleted?

### ISSUE THREAD

**Issue by inanimateobject** [blueprint-freespeech/ricochet-refresh#160]
I just realized that the newest release has been recently deleted so I wondered if it is still safe to use or if one should downgrade? Was there a vulnerability?

Btw: What is up with the changed license. Why using a proprietary one all of a sudden.

**Comment by pospeselr** [comment]
previous release had some issues, license change has been reverted and new 3.0.12 tag/builds should be ready this weekend.

**Comment by inanimateobject** [comment]
Sorry to ask but what kind of "issues"?

**Comment by pospeselr** [comment]
the afore-mentioned licensing problems, the non-deterministic #150 crash, and 0.4.7.7 tor had a security vulnerability which updating to 0.4.7.8 will fix (see: https://forum.torproject.net/t/stable-release-0-4-7-8/3679 )
