### ISSUE TITLE
Sound notifications still not working in most recent version 3.0.13

### ISSUE THREAD

**Issue by 1iqu1dsnake** [blueprint-freespeech/ricochet-refresh#164]
I have noticed that in the most recent version, 3.0.13, the sound notifications still aren't working. It would be nice to know when I'm getting a message. At the least, even a silent pop up chat bubble would be sufficient. Please address and fix this issue thanks!

I last posted about this issue here: https://github.com/blueprint-freespeech/ricochet-refresh/issues/147

**Comment by pospeselr** [comment]
Dupe https://github.com/blueprint-freespeech/ricochet-refresh/issues/147
