### ISSUE TITLE
Build error on Ubuntu 18.04.6

### ISSUE THREAD

**Issue by greenpark-code** [blueprint-freespeech/ricochet-refresh#166]
````
myPath/ricochet-refresh$ cmake -S ./src -B ./build -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=MinSizeRel -DRICOCHET_REFRESH_INSTALL_DESKTOP=ON
CMake Error: The source directory "myPath/ricochet-refresh/build" does not appear to contain CMakeLists.txt.
````

Surprise: it looks for that file in the build subfolder instead of the src one.

````
$ less src/CMakeLists.txt
[...]
cmake_minimum_required(VERSION 3.16)
[...]
````

````
$ cmake --version
cmake version 3.10.2
````

````
$ sudo apt-get install cmake
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cmake is already the newest version (3.10.2-1ubuntu2.18.04.2).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
````

([On the other hand](https://github.com/blueprint-freespeech/ricochet-refresh/issues/152), Ubuntu 18.04.6 has glibc-2.27.)

**Comment by pospeselr** [comment]
look like you need to update your cmake to at least 3.16

**Comment by greenpark-code** [comment]
> look like you need to update your cmake to at least 3.16

Thanks!

Truth is: I should install a recent Linux on this PC... and also buy a new PC (but I'm rather busy trying to have a distributed dbase running on raspberry PIs).
