### ISSUE TITLE
segfaults on NixOS

### ISSUE THREAD

**Issue by theotheroracle** [blueprint-freespeech/ricochet-refresh#175]
i'm running nixos 23.05-unstable, and when i try to run the x86_64.appimage, i get the error 
fish: Job 1, './Ricochet_Refresh-156ddee-x86_…' terminated by signal SIGSEGV (Address boundary error)

**Comment by theotheroracle** [comment]
the tar.gz version gives the same result

**Comment by pospeselr** [comment]
That's *interesting*. Does ricochet-refresh also crash the same way if you build from source locally (you won't have pluggable-transports and it will need a tor binary to exist in $PATH).

Doesn't crash on x86_64 Linux Mint 21.1  vOv

**Comment by theotheroracle** [comment]
let me try

**Comment by theotheroracle** [comment]
i tried to build it but i ran into this error:
[logs.txt](https://github.com/blueprint-freespeech/ricochet-refresh/files/12167985/logs.txt)

**Comment by theotheroracle** [comment]
alright ! i found the issue, fmt was too new, and now i got it built, but i'm getting a different error now

**Comment by theotheroracle** [comment]
here's the package if you wanna try it on your system, you'll just need install nix, and then clone the repo and run `nix run`

**Comment by theotheroracle** [comment]
alright i figured out the issue was just not being able to find tor, and i fixed that so i have a working package now !

**Comment by pospeselr** [comment]
@theotheroracle so is this donwnstream packaging issue on the NixOS side or something else? 

So one issue you *may* run into with a new package is that Ricochet-Refresh assumes that it runs/controls its own shipped tor daemon and that the pluggable transports are in a particular location relative to the ricochet-refresh binary's location on disk. So I guess make sure PTs are working as expected?

**Comment by theotheroracle** [comment]
the issue with the package not being able to find tor is just a dowstream issue, the issue with the appimage segfaulting i don't understand what the issue

**Comment by theotheroracle** [comment]
using [this tool](https://nixos.wiki/wiki/Appimage) the appimage runs fine, sorry for the confusion, but i also still intend to get the package upstreadmed in nixos !

**Comment by pospeselr** [comment]
Awesome! Thanks for following up!
