### ISSUE TITLE
Split the GUI into a Tor-Connection-Tool and a Messenger-App based on it

### ISSUE THREAD

**Issue by Sammysupport** [blueprint-freespeech/ricochet-refresh#189]
Please make the Tor-Tab of RicoChet an own tool 
(e.g. probably merged with GUI elements of revived vidalia) 
and a Messenger App RicoChet.

(Does it make sense, that each App starts an own Tor.exe (with path to exe, Port, path to torrc-config.file, bunch of connections and routes etc))?

With Qt the Gui for the Tor-Tab also can be hoocked up as an own Window - so it would be near of an own process (and e.g. be dropped if vidalia is revived, if a common deamon of Torbrowser is addressed, or a system tor-deamon is given or another library api can be addresses within the apps).

**Comment by pospeselr** [comment]
See my post in https://github.com/blueprint-freespeech/ricochet-refresh/issues/188 for further detail on why this sort of thing shouldn't be encouraged.
