### ISSUE TITLE
Static build not working

### ISSUE THREAD

**Issue by dartmann** [blueprint-freespeech/ricochet-refresh#19]
Hi there, I tried to build a statically linked version of the original Ricochet IM client for Ubuntu 18.04. I know ricochet-refresh is its successor and therefore not directly the correct place for my issue. Anyway I hope that somebody can help me out. I am pretty sure that I won't get an answer when I open an issue in the old repo.

My problem is, that the compiled binary won't start with the error: `qrc:/ui/main.qml:1 module "QtQuick" plugin "qtquick2plugin" not found`. A quick research about this error got me no real help but the information that statically linked Qt programs [can not load plugins](https://stackoverflow.com/questions/13591951/module-qtquick-plugin-qtquick2plugin-not-found-in-static-linked-application) - but the prebuild binaries are working (and so a static build).

Hopefully somebody can help me. I would also love to read a description of how to succefully build a statically linked version of the Ricochet Refresh client, because I was not able to run your modifed build scripts in `buildscripts/linux-static` as they should.

Thank you, David

**Comment by pospeselr** [comment]
This bug is a bit obsolete, as the old buildscripts have been removed in alpha and build moved to https://github.com/pospeselr/ricochet-build (a fork of Tor Project's tor-browser-build: https://gitweb.torproject.org/builders/tor-browser-build.git/

We do need to update our documentation for doing dev builds for each platform.

**Comment by milahu** [comment]
> I was not able to run your modifed build scripts

why?

> Hopefully somebody can help me.

so you need a dynamic build of ricochet.
when i build ricochet-refresh with qmake, i get a dynamic executable:

```
$ ldd /nix/store/m2yihaibiqwidhhn93cncv671as9fs83-ricochet-refresh-3.0.10/bin/.ricochet-refresh-wrapped | grep -i quick 
        libQt5Quick.so.5 => /nix/store/fnn8pbyfm5zgrfibg7m0xknx5x1s9a95-qtdeclarative-5.15.2/lib/libQt5Quick.so.5 (0x00007f4648d10000)
```

**Comment by m-simonelli** [comment]
Same reason as #106

**Comment by m-simonelli** [comment]
Same reason as #106
