### ISSUE TITLE
Security: UI Redressing / Shared File Names can contained HTML

### ISSUE THREAD

**Issue by s-rah** [blueprint-freespeech/ricochet-refresh#195]
Users can share files with names that contain a restricted subset of HTML https://doc.qt.io/qt-6/richtext-html-subset.html - this allows the remote peer some degree of control over the messaging page, including the ability to format text and links and potentially include images.

![Screenshot_2024-09-20_10-14-09](https://github.com/user-attachments/assets/c568f7d2-27ba-437d-b5be-cb9ee24c4d1b)

Note: Image inclusion is limited because RR rejects files containing forward slashes, and by default QML assumes the URI is a qrc resource (and there are no images in the default qrc root) - however I've not done extensive testing here so I wouldn't rule out the possibility of being able to load an image using this method (locally or otherwise).

**Comment by morganava** [comment]
ffs

**Comment by morganava** [comment]
Ok at least links aren't clickable and we're doing the right thing for normal messages:
![image](https://github.com/user-attachments/assets/6f9e9d37-a0d4-4734-8467-d5c0716a2b97)

Working on a patch, thx Sarah!

**Comment by morganava** [comment]
One-line fix fortunately:
![image](https://github.com/user-attachments/assets/c48210ea-f7dc-461b-90bd-455693e68c1f)
Will push a new release later today.

**Comment by morganava** [comment]
Fixedin 498bcf90b2f50599dba1a5bfd130620a08543a0f

**Comment by morganava** [comment]
Fixed as of Ricochet-Refresh 3.0.27
