### ISSUE TITLE
Suggestion: Focus on the Service.  Do not include Tor.

### ISSUE THREAD

**Issue by DiagonalArg** [blueprint-freespeech/ricochet-refresh#2]
Thanks for taking up this project.  While I'm not much of a developer, I can see that ricochet includes Tor, which is a fine way to make sure it becomes rapidly obsolete.  I wonder if you would want to focus only on the task of creating the service, which would then be linked to an already running Tor service?  

[Edit] I'm just discovering that there is such thing as an "ephemeral onion services" and that [onionshare](https://github.com/micahflee/onionshare/)/[onionize](https://github.com/nogoegst/onionize) are using it.  Perhaps that's the way to go with ricochet?  Here is [a description](https://tor.stackexchange.com/a/10682/1064).

References - [ricochet-im](https://github.com/ricochet-im/ricochet/issues/600#issuecomment-506935528) and @cypherbits

**Comment by noneuclideangirl** [comment]
I absolutely agree and I think including a build is not the best way to go about it. Will definitely check out this ephemeral onion service business!

**Comment by cypherbits** [comment]
As I said on main ricochet:
The goal of including Tor with Ricochet is that people with no system-wide Tor, like Windows users can use Ricochet easily. Ephemeral onion services make easy for Ricochet to manage many identities but you need Tor to connect to Tor xD

**Comment by DiagonalArg** [comment]
I'll just refer to [my comment there](https://github.com/ricochet-im/ricochet/issues/601#issuecomment-510070869).

**Comment by PeterTonoli** [comment]
I feel this is a usability issue. While you & I might have the nous to update Tor, some of Ricochet's users might not.

Regular updates of Ricochet will mitigate this problem.

Please include Tor.

**Comment by DiagonalArg** [comment]
Well, if you want to go that way, I'd modify that to say "Please include tor *only if the developer intends to update ricochet/ricochet-refresh every time tor updates*."  Otherwise, [it's just making it easy for users to screw up](https://github.com/ricochet-im/ricochet/issues/601#issuecomment-511929524).

**Comment by timkuijsten** [comment]
The original Ricochet simply looks for a system-wide version of Tor if the included (and by now hopelessly outdated) Tor binary is not there. This helped me maintian Ricochet on all supported platforms remarkably well, as I've documented here: https://netsend.nl/ricochet.

**Comment by odiferousmint** [comment]
Ephemeral onion services are completely separate from not bundling Tor. Creating an ephemeral hidden service means that you create a new private key every single time,  which means a new identity with respect to Ricochet. Ricochet saves your private key in `ricochet.json` as `serviceKey` and passes it to`Tor::HiddenService` upon creation. So, to use `ephemeral hidden service` means to create a new identity every time you start Ricochet. Your Ricochet ID is going to be different, and so forth. It is not inherently a good thing. That said, I can imagine this as a setting.

As far as bundling Tor goes, there are two ways to customize the Tor executable path: 1) if you are compiling it from source, define `BUNDLED_TOR_PATH`, or 2) in `ricochet.json` which Ricochet loads on startup, add:

```json
{
    "tor": {
        "executablePath": "/usr/bin/"
    }
    [...]
}
```

Or just place the Tor executable in the same directory where the Ricochet executable is.

**Comment by DiagonalArg** [comment]
> Ephemeral onion service is completely separate from the bundling of Tor.

If tor is running as a daemon, then this will allow you to start a service through the already running tor.  I see what you are saying above and may open another issue on this.  Thanks.

> in ricochet.json which Ricochet loads on startup, add ... [above]

Thank you, that's useful.

> FWIW: I think that defaulting to using ./tor or ./tor.exe is optimal, 

That's fine, if you want a tor specifically running for ricochet.

> and Tor should be bundled because if you do not bundle Tor, you rely on having it installed by someone under the default or customized Tor executable path, which is extra work, and it will not work out-of-the-box, which I believe is an issue for a lot of people.  

That is also fine if:

> As Peter has said, "regular updates of Ricochet will mitigate this problem", 

On  the other hand, the fact is that there have not been regular updates of Ricochet - far from it.  So **if** Ricochet is regularly updated, then bundling tor might make sense as it makes it easy for people who don't know how to install it.  On the other hand, **if** Ricochet is not regularly updated, which is absolutely the case, then bundling tor makes it easy for people who don't know how to install it to shoot themselves in the foot.  So **if** you don't want people shooting themselves in the foot, and you are not going to update Ricochet immediately every time tor is updated, then you won't bundle tor with it.  (That's a logical tautology - check it.)  

> or you might as well just set the executable path yourself and/or update Tor yourself. It is a non-issue.

There we disagree.  Unless updates happen immediately on update of tor, you will be seducing people who don't know what they are doing into thinking they are safe.

**Comment by odiferousmint** [comment]
> On the other hand, if Ricochet is not regularly updated, which is absolutely the case, then bundling tor makes it easy for people who don't know how to install it to shoot themselves in the foot. So if you don't want people shooting themselves in the foot, and you are not going to update Ricochet immediately every time tor is updated, then you won't bundle tor with it. (That's a logical tautology - check it.)

People who do not know how to install and/or update Tor will not be able to use Ricochet. Ricochet depends on Tor. Just for clarification, are you suggesting that this should be the case?

> you will be seducing people who don't know what they are doing into thinking they are safe

OK, what can we do about this right now, as people who have no write access to the project? We can note somewhere that the current version of the bundled Tor is outdated, we can add instructions as to how to update Tor, and we can tell users the same thing I told you regarding Tor executable path customization. We should also note that updating Tor is not enough. Ricochet needs to switch from `RSA1024` to `ED25519-V3` at the very least.

In any case, you are saying that Ricochet should not bundle Tor because it (Ricochet) is not regularly updated. What you are asking here is for developers to make a change to Ricochet, i.e. update Ricochet. If they are going to do that, they might as well just continue bundling Tor and update the version. :)

**Comment by pospeselr** [comment]
Tor is bundled in alpha builds, uses ephemeral onion services and has made the switch to E25519-V3 based onion services. We do need a good plan for UX (and backend work) for specifying whether to use an existing running system tor service, and whether to launch a new instance of the system tor or the bundled tor. Currently ricochet-refresh launches its own bundled tor.

**Comment by milahu** [comment]
> use an existing running system tor service

still an issue

related

- #101 
- #102 

([via whonix.org](https://www.whonix.org/wiki/Chat#Ricochet_IM))

**Comment by DiagonalArg** [comment]
@milahu / "[deprecated](https://www.whonix.org/wiki/Chat#Ricochet_IM)"

Try: https://docs.cwtch.im/download/

**Comment by milahu** [comment]
> "[deprecated](https://www.whonix.org/wiki/Chat#Ricochet_IM)"

can you read?

> **Ricochet** IM (original) is no longer recommended as a decentralized (server-less) option because it is not functional in Whonix and **deprecated** upstream by its original developers.

Ricochet != Ricochet Refresh

**Comment by DiagonalArg** [comment]
> can you read?

<img width="282" height="294" alt="Image" src="https://github.com/user-attachments/assets/909254ad-d7dd-4b2f-aac7-1c18a02d9431" />

<img width="962" height="533" alt="Image" src="https://github.com/user-attachments/assets/da78dd7c-c2e6-49fc-974b-92861de3fb79" />

**Comment by milahu** [comment]
i already know youre an idiot
no need to post screenshots of text to further confirm your stupidity

ricochet-refresh is not deprecated

**Comment by DiagonalArg** [comment]
When they go ballistic, it usually means you're somewhere approaching the target.

**Comment by morganava** [comment]
FYI support for this could be added in the current main branch now via: https://gosling.technology/crates/src/tor_interface/legacy_tor_client.rs.html#185

Would require:
- a bit of plumbing through the FFI
- disabling the Configure button on the bootstrap/connect window when using env variables

These changes would only appear in the alpha-channel however since the maint-3.0 channel is not using the new backend.
