### ISSUE TITLE
Ubuntu 20.10 Ricochet 3.0.0-alpha "error while loading shared libraries: libxcb-icccm.so.4: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by bungabunga** [blueprint-freespeech/ricochet-refresh#23]
Ubuntu 20.10 and Ricochet Refresh 3.0.0-alpha

**Comment by pospeselr** [comment]
Linux builds (currently) depend on various shared libraries (including libxcb). See ricochet-refresh's build config ( https://github.com/blueprint-freespeech/ricochet-build/blob/master/projects/tego/config#L41 ) for the full list.

We should add a README to our Linux package with full list of libs we need users to install.

**Comment by pospeselr** [comment]
You should use the deb or AppImage packages if you are unsure of how to install dependencies
