### ISSUE TITLE
Replace regex engine

### ISSUE THREAD

**Issue by eleanor-em** [blueprint-freespeech/ricochet-refresh#4]
Sarah mentioned in correspondence that the regex engine has some known issues. This should be looked into, and probably replaced.

**Comment by z3ndrag0n** [comment]
@noneuclideangirl any further information available?

**Comment by pospeselr** [comment]
Regex is currently only used to first-pass validate ricochet ids (which are really v3 onion service ids). Our ED25519-V3 code ensure the ids are actually valid v3 onion service ids.
