### ISSUE TITLE
Make obtaining Bridges easier

### ISSUE THREAD

**Issue by PacoBell** [blueprint-freespeech/ricochet-refresh#65]
Maybe implement the MOAT protocol like in Tor Browser?

https://github.com/isislovecruft/bridgedb#accessing-the-moat-interface

**Comment by pospeselr** [comment]
Yeah getting Ricochet-Refresh working with the broader bridge ecosystem is on our radar

**Comment by pospeselr** [comment]
Partially resolved in 3.0.12
