### ISSUE TITLE
Crash on adding invalid contact ID

### ISSUE THREAD

**Issue by m-simonelli** [blueprint-freespeech/ricochet-refresh#66]
Steps to reproduce:
1. Open add contact window
2. Enter an invalid ID (i.e.: `ricochet:ajz7hutxg67rsw56vcvblqsa36jymxsqzutkbdspcazeddzvdjaok3ia`)

**Comment by pospeselr** [comment]
fixed in https://github.com/blueprint-freespeech/ricochet-refresh/commit/1e83d96400b1dbff811e434fbb4278379c7d2e90
