### ISSUE TITLE
[Request] Command line interface

### ISSUE THREAD

**Issue by beantaco** [blueprint-freespeech/ricochet-refresh#80]
Instead of launching the GUI, it would be nice to be able to operate Ricochet Refresh in a terminal with a command line interface (CLI) using just the keyboard.

Assuming a CLI exists, Ricochet Refresh could be invoked in a command line terminal with a flag like `--cli` or `-C` or something appropriate.

**Comment by pospeselr** [comment]
This would be an entirely different app, but in theory once gosling is finished this would be feasible for someone to take a stab at.

**Comment by milahu** [comment]
> it would be nice to be able to operate Ricochet Refresh in a terminal

thats called a [terminal user interface](https://github.com/rothgar/awesome-tuis#messaging) = TUI

> command line interface (CLI)

that would be something like

```
ricochet-refresh --config ~/.config/ricochet-refresh-2
```

...which would be needed to run multiple ricochet instances on one machine
which currently fails with the error `Configuration file is already in use`

workaround:

```
HOME=$HOME/.config/ricochet-refresh-2 ricochet-refresh
```
