### ISSUE TITLE
Enable users to export conversation as a text file

### ISSUE THREAD

**Issue by pospeselr** [blueprint-freespeech/ricochet-refresh#84]
This will require a couple pieces of work:

- UI to initiated an export; this should probably mirror the Send File... command in the context menu when right-clicking on a contact
- We will want to export chats with timestamps, along with relevant events (login, logoff, file transfer initiation/acceptance/cancelling/errors/etc)
- Login/loggoff events would requrie a bit of refactoring of ConversationModel to record login/loggoff events, and could come in in a later patch (or we can ignore these :shrug: )

**Comment by m-simonelli** [comment]
Resolved in #93
