### ISSUE TITLE
Split TEGO_VERSION into two macros so that windows builds can have non-numerical names

### ISSUE THREAD

**Issue by pospeselr** [blueprint-freespeech/ricochet-refresh#87]
Currently the TEGO_VERSION in tego_ui.pro ultimately gets used in multiple ways, including in generating the FILE_VERSION member of the resources.rc file for the windows binary which MUST be a x.x.x.x number. We should split out a TEGO_NAME from TEGO_VERSION so that the places where TEGO_VERSION is being used as a name can remain, while not breaking windows builds.

We will also need to update ricochet-build to take advantage of this change.

**Comment by m-simonelli** [comment]
@pospeselr I'm not sure if this applies any more since the CMake migration?
